services:
- docker
script:
- docker build -t cliwrap/xenial .
# Check user id
- >
  docker run --rm -e "HOSTUID=`id -u`" -v "`pwd`:/work" cliwrap/xenial
  id -u 2>&1 | grep "^`id -u`$"
# Check group id
- >
  docker run --rm -e "HOSTUID=`id -u`" -e "HOSTGID=`id -g`" -v "`pwd`:/work"
  cliwrap/xenial id -g 2>&1 | grep "^`id -g`$"
# Create a file
- >
  docker run
  --rm
  -e "HOSTUID=`id -u`"
  -v "`pwd`:/work"
  cliwrap/xenial
  touch ActapWuSwyk2
  2>&1 && [ -f ActapWuSwyk2 ]
# Make sure the container works normally
- docker run --rm cliwrap/xenial whoami | grep '^root$'
# Make sure the container works normally
- docker run --rm cliwrap/xenial pwd | grep '^/$'
# Test volume mount only
- docker run --rm -v "`pwd`:/work" cliwrap/xenial pwd | grep '^/work$'
# Test volume mount only
- docker run --rm -v "`pwd`:/work" cliwrap/xenial whoami | grep '^root$'
# Test user id only
- docker run --rm -e "HOSTUID=`id -u`" cliwrap/xenial pwd | grep '^/home/hostuser$'
# Test user id only
- docker run --rm -e "HOSTUID=`id -u`" cliwrap/xenial whoami | grep '^hostuser$'
# Make sure it is still possible to use apt
- docker run --rm cliwrap/xenial sh -c "sudo apt-get update && sudo apt-get -y install less"
# Make sure it is still possible to use apt
- docker run --rm cliwrap/xenial sh -c "sudo apt-get update && sudo apt-get -y install texlive-latex-base"
# Make sure environment passed through
- >
  docker run --rm -e FOOBAR=baz -e "HOSTUID=`id -u`" -e "HOSTGID=`id -g`" -v "`pwd`:/work"
  cliwrap/xenial env | grep "^FOOBAR=baz"
after_success:
- >
  curl -H "Content-Type: application/json"
  --data '{"source_type": "Branch", "source_name": "master"}'
  -X POST
  https://hub.docker.com/api/build/v1/source/30cc9d30-ee98-46d3-80d4-01d3e961649b/trigger/658768b1-3335-474c-baae-cbf313321c4a/call/
notifications:
  email:
    recipients:
      secure: HhCb2BHSWsrIkgc0z7hyCVjr9SIdKe76mw9mmj7PeIj7lSdslX3/S/6tLsBPngK8e6NxbKkSWGVxL9aWgPnS1H2Di/5RgJCKkBpiVsrfLgNJXfaMw7UAEnfehruYwn541GRxOgT8WMEU4vP52OWthxyJmQ21QbSoUmYQOpAjLTxQ/+0DNied5kHOUIamy7gbl8WeBPm8018Z3XJwbAUxIetuhhoXYHnLlZ7hMzlGKJisf4upDznp6fJMtoxNpdFa7Vr5G6vuQMOdIGpM6Iz3sss4NNGhiA4CPDEzoiIvFhhuNubKyOLcnZs6Y4h+mNZw8zHJWovo75fViBDxH+4UJYAr5aP7ZOIAe2QBnRcwtDKjkBglF3LmjpXLKSyYQn0BzAwJ1zHHPt/1b58WNT9qFRHd0Lnoh5hfdDVBscds9M0Itg5k6sUK8MBVvmCgNQ9MdmdGn8W7lWakA+PvuZsSYMG/fKcPt1ode90homcRRkpMI9XRMdbOzIoc3P7Nn8H7+gLSorpRCqdTRDESf+aXl389DHCcQr7HkhXqAO3aaS0OY8Yvo+ZE8sirx9RLMbrNsfmFMZt2gn0gRTdNVbSwA4X4lZ4Yt94AlA0ryBMeWSJQ4/vksU7u5ycfp0Z2q1sGBspj8IIhWKQUCnxnFh4N4GcpvmT9VC8SQryuHh70gSY=
